# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################

cart: {}

catalogue: {}

dispatch: {}

mongodb: {}

mysql: {}

payment:
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com

rabbitmq: {}

ratings: {}

redis:
  # Storage class to use with redis statefulset.
  storageClassName: standard

shipping:
  env:
    - name: JAVA_TOOL_OPTIONS
      value: "-javaagent:/instana/agent/instana-agent.jar"
    - name: INSTANA_AGENT_KEY
      value: "hops0zfQTiqMVetWMNzjWA"
    - name: INSTANA_AGENT_ENDPOINT
      value: "https://instana-0.ibmdte.local"
  volumeMounts:
    - name: instana-agent
      mountPath: /instana/agent
      readOnly: true
  volumes:
    - name: instana-agent
      hostPath:
        path: /opt/instana/agent
        type: Directory


user: {}

web: {}
